export const cities = [
  "Hà Nội",
  "Thành phố Hồ Chí Minh",
  "Đà Nẵng",
  "Remote",
  "An Giang",
  "Bà Rịa - Vũng Tàu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bạc Liêu",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Định",
  "Bình Dương",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cần Thơ",
  "Cao Bằng",
  "Đắk Lắk",
  "Đắk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Tĩnh",
  "Hải Dương",
  "Hải Phòng",
  "Hậu Giang",
  "Hòa Bình",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "Lai Châu",
  "Lâm Đồng",
  "Lạng Sơn",
  "Lào Cai",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Ninh Thuận",
  "Phú Thọ",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yên Bái",
];

export const jobCategories = [
  { id: "engineer", text: "Engineer" },
  { id: "engineering_manager", text: "Engineering Manager" },
  { id: "product_manager", text: "Product Manager" },
  { id: "project_manager", text: "Project Manager" },
  { id: "designer", text: "Designer" },
  { id: "business_analyst", text: "Business Analyst" },
  { id: "other", text: "Khác" },
];

export const jobCategoriesMap = {};
jobCategories.forEach((category) => {
  jobCategoriesMap[category.id] = category.text;
});

export const jobFocuses = [
  { id: "ios", text: "iOS" },
  { id: "android", text: "Android" },
  { id: "web_frontend", text: "Web Frontend" },
  { id: "backend", text: "Backend" },
  { id: "fullstack", text: "Fullstack" },
  { id: "devops", text: "DevOps" },
  { id: "sre", text: "SRE" },
  { id: "embedded", text: "Embedded" },
  { id: "security", text: "Security" },
  { id: "hardware", text: "Hardware" },
  { id: "qa", text: "QA" },
  { id: "system_administrator", text: "System Admin" },
];

export const jobFocusesMap = {};
jobFocuses.forEach((focus) => {
  jobFocusesMap[focus.id] = focus.text;
});
